version: "3.9"
services:
  ora-db:
    image: postgres
    restart: always
    container_name: ora-db
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: harshal
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres: